/** 图片署名。CC0 与免署名 Unsplash 图不逐条列出，见 UNSPLASH_NOTE 总述。 */
export interface ImageCredit {
  /** 商品 id；编辑配图（ed-*）没有对应商品，靠 label 显示中文名 */
  productId: string
  title: string
  creator: string
  license: string
  sourceUrl: string
  /** 非商品图（编辑配图）的中文标题，商品图留空则回退到商品名 */
  label?: string
}

/** 未逐条署名的图片总述（Unsplash 免署名图 + CC0 图源）。 */
export const UNSPLASH_NOTE =
  'The remaining images are either photographs from Unsplash (attribution-free) and CC0 public-domain sources, or generated by the catalogue image pipeline. All were inspected by eye to carry no readable brand marks. Pieces without a suitable image show an auction-catalogue plaque instead.'

export const IMAGE_CREDITS: ImageCredit[] = [
  { productId: 'ed-atelier', title: "An artisan's hands adjusting a movement in dim light", creator: 'Tahlia Doyle', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/bfk68pL0EJ0', label: "An artisan's hands adjusting a movement in dim light" },
  { productId: 'ed-atelier-2', title: "Hand tools lined up on the atelier's dark wall", creator: 'Minh Đức', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/2gu0SU7_kr4', label: "Hand tools lined up on the atelier's dark wall" },
  { productId: 'ed-vault', title: 'A closed round steel vault door, bolts in a ring', creator: 'Alex Duffy', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/1AucbckEJWk', label: 'A closed round steel vault door, bolts in a ring' },
  { productId: 'ed-vitrine', title: 'An empty stone hall, the vitrines quieter than the exhibits', creator: 'Simon Ray', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/16tANB-VhsY', label: 'An empty stone hall, the vitrines quieter than the exhibits' },
  { productId: 'lx-croc-cardcase', title: 'a black wallet sitting on top of a metal rail', creator: 'CHUTTERSNAP', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/W9kn44uJIDk' },
  { productId: 'lx-zero-clutch', title: 'A brown leather clutch sits on a wooden surface', creator: 'Ocult Store', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/K78mXNm0zdM' },
  { productId: 'lx-cremona-violin', title: 'Violin, Figaro House, Vienna', creator: 'cphoffman42', license: 'CC BY-SA', sourceUrl: 'https://www.flickr.com/photos/23088289@N02/3325997340' },
  { productId: 'lx-triple-crown-colt', title: 'a close up of a horse\'s face in the dark', creator: 'Martin Baron', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/a-close-up-of-a-horses-face-in-the-dark-Jld3OYJFnSE' },
  { productId: 'lx-single-cask-70', title: 'barrels of liquor in a basement', creator: 'Eric Cook', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/barrels-of-liquor-in-a-basement-D9WH_vlxicA' },
  { productId: 'lx-private-chef-year', title: 'cooked food on black round plate', creator: 'Trình Minh Thư', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/cooked-food-on-black-round-plate-a6kYPun9_ao' },
  { productId: 'lx-sommelier-year', title: 'person pouring red wine on wine glass', creator: 'Lefteris kallergis', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/person-pouring-red-wine-on-wine-glass-etWlaoFnTl4' },
  { productId: 'lx-bridal-couture', title: 'A strapless white gown on a mannequin in a window', creator: 'Sou Jest', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/a-strapless-white-gown-on-a-mannequin-in-a-window-tTn-X7huVbI' },
  { productId: 'lx-skyflat-duplex', title: 'Modern living room with large windows and city view', creator: 'Caroline Badran', license: 'Unsplash', sourceUrl: 'https://unsplash.com/photos/modern-living-room-with-large-windows-and-city-view-DhVAndFPb3k' },
]
