/* 由 scripts/build-image-manifest.mjs 生成，请勿手改。

   IMAGE_VIEWS：商品 id → 已有的图录视角数（1 = 只有主图，3 = 全貌/另一角度/细节）。
   未列出的商品没有照片，走丝绒展签兜底——缺图不是错误。 */

export const IMAGE_VIEWS: Record<string, number> = {
  'lx-alba-truffle': 1,
  'lx-alligator-lock': 3,
  'lx-alpine-chalet': 1,
  'lx-antimatter-futures': 1,
  'lx-arab-racehorse': 1,
  'lx-armored-saloon': 1,
  'lx-asteroid-mining': 1,
  'lx-asteroid-name': 1,
  'lx-auction-cover': 1,
  'lx-av-fleet': 1,
  'lx-baby-cashmere': 1,
  'lx-blue-diamond-ring': 3,
  'lx-bordeaux-vertical': 1,
  'lx-bridal-couture': 1,
  'lx-british-gt': 1,
  'lx-butler-tenure': 1,
  'lx-caribbean-cay': 1,
  'lx-catamaran-42': 1,
  'lx-caviar-quota': 1,
  'lx-centre-court': 1,
  'lx-chenghua-chickencup': 3,
  'lx-coachbuilt-one-off': 3,
  'lx-collider-beamtime': 1,
  'lx-commercial-fusion': 1,
  'lx-concert-grand': 1,
  'lx-couture-gown': 1,
  'lx-cremona-violin': 1,
  'lx-croc-birkin': 1,
  'lx-croc-cardcase': 1,
  'lx-croc-vanity': 3,
  'lx-d-flawless': 1,
  'lx-daytona-steel': 3,
  'lx-diamond-parure': 3,
  'lx-emerald-garden': 1,
  'lx-emerald-riviere': 3,
  'lx-en-primeur': 1,
  'lx-endurance-legend': 3,
  'lx-esports-arena-name': 3,
  'lx-explorer-60': 1,
  'lx-f1-paddock': 1,
  'lx-f1-roadcar': 3,
  'lx-f1-team-share': 3,
  'lx-festival-carpet': 3,
  'lx-flagship-gpu': 1,
  'lx-fresco-fragment': 1,
  'lx-fusion-share': 1,
  'lx-gigayacht-110': 1,
  'lx-glacier-cubes': 1,
  'lx-goat-lesson': 1,
  'lx-gpu-cluster': 1,
  'lx-grande-sonnerie': 3,
  'lx-heavy-jet': 1,
  'lx-helium3-mining': 3,
  'lx-himalaya-croc': 1,
  'lx-humanoid-butler': 1,
  'lx-hydrogen-jet': 3,
  'lx-hyper-coupe': 3,
  'lx-icebreaker-yacht': 1,
  'lx-imperial-dragon-robe': 1,
  'lx-impressionist-harbor': 3,
  'lx-indian-atoll': 3,
  'lx-inference-farm': 1,
  'lx-jade-bangle': 3,
  'lx-kyoto-chakai': 1,
  'lx-landing-pad': 1,
  'lx-leather-globe': 3,
  'lx-leo-constellation': 1,
  'lx-leo-satellite': 1,
  'lx-light-jet': 1,
  'lx-lily-corner': 1,
  'lx-links-membership': 1,
  'lx-loire-chateau': 1,
  'lx-lunar-datacenter': 1,
  'lx-maglev-concept': 3,
  'lx-megawatt-cluster': 1,
  'lx-midsize-jet': 1,
  'lx-mining-haul-truck': 3,
  'lx-moon-acre': 1,
  'lx-mothership-fleet': 1,
  'lx-nautilus-blue': 3,
  'lx-naval-reactor': 1,
  'lx-ostrich-tote': 3,
  'lx-pacific-island': 1,
  'lx-personal-stylist': 1,
  'lx-pet-carrier-croc': 3,
  'lx-pink-diamond-ring': 3,
  'lx-postimpressionist-study': 1,
  'lx-prewar-grand-prix': 3,
  'lx-private-chef-year': 1,
  'lx-quantum-hour': 1,
  'lx-red-diamond-solitaire': 2,
  'lx-redcarpet-look': 1,
  'lx-river-flat': 1,
  'lx-royal-sapphire': 1,
  'lx-sable-coat': 3,
  'lx-savile-suit': 1,
  'lx-scottish-castle': 3,
  'lx-seven-summits-guide': 3,
  'lx-silk-carre': 1,
  'lx-single-cask-60': 1,
  'lx-single-cask-70': 1,
  'lx-sky-penthouse': 1,
  'lx-sky-pool-duplex': 1,
  'lx-skyflat-duplex': 1,
  'lx-solar-circumnav': 1,
  'lx-sommelier-year': 1,
  'lx-song-porcelain': 1,
  'lx-south-sea': 1,
  'lx-space-solar': 1,
  'lx-space-station-seat': 1,
  'lx-submersible-yacht': 3,
  'lx-suborbital-seat': 1,
  'lx-sunrise-charter': 1,
  'lx-supercar-key': 1,
  'lx-supersonic-jet': 3,
  'lx-superyacht-72': 1,
  'lx-superyacht-76': 1,
  'lx-superyacht-85': 1,
  'lx-superyacht-95': 3,
  'lx-swan-wedding': 3,
  'lx-tea-master-life': 1,
  'lx-thousand-cluster': 1,
  'lx-tiltrotor': 1,
  'lx-titanium-moto': 1,
  'lx-topological-qubit': 1,
  'lx-tourbillon-minute': 1,
  'lx-trimaran-yacht': 1,
  'lx-triple-crown-colt': 1,
  'lx-tug-explorer': 1,
  'lx-twin-heli': 1,
  'lx-ultralong-jet': 1,
  'lx-v12-coupe': 1,
  'lx-vicuna-scarf': 1,
  'lx-vintage-racer': 1,
  'lx-vip-widebody': 3,
  'lx-vivid-yellow': 3,
  'lx-wafer-share': 1,
  'lx-wavepool-title': 3,
  'lx-wingsail-concept': 1,
  'lx-world-cruise': 1,
  'lx-wrap-it-all': 1,
  'lx-yuan-blueandwhite': 1,
  'lx-zero-clutch': 1,
}

/** 分类 → 各视角的图录小字。与 scripts/art-direction.mjs 里生成图片的视角一一对应。 */
export const VIEW_CAPTIONS: Record<string, string[]> = {
  '包袋皮具': ['Full view', 'Reverse', 'From above'],
  '腕表珠宝': ['Full view', 'Profile', 'From above'],
  '尊贵座驾': ['Full view', 'Reverse', 'From above'],
  '游艇航空': ['Full view', 'From above', 'Reverse'],
  '不动产': ['Exterior', 'Interior', 'From above'],
  '科技算力': ['Full view', 'Profile', 'Reverse'],
  '运动竞技': ['Full view', 'From above', 'Ground level'],
  '酒窖餐桌': ['Full view', 'Profile', 'From above'],
  '高定衣橱': ['Full view', 'Reverse', 'Profile'],
  '艺术收藏': ['Full view', 'Raking light', 'In situ'],
}

/** 有照片的商品数（其余走展签） */
export const PHOTOGRAPHED_COUNT = 143
