#!/usr/bin/env node
/**
 * 商品配图流水线（Flux via Pollinations，免费无 key）。
 *
 * 为什么长这样：Pollinations 匿名档 **每 IP 只允许 1 个并发**（并发请求直接 429），
 * 且持续请求会被限速到 ~40s/张（换 turbo 也一样，可见限的是 IP 不是算力）。
 * 所以本脚本是严格串行 + 自适应退避 + **可续跑**的。1009 件 × 3 视角 = 2900+ 张，
 * 按这个速率是 30 多个小时——跑不完是常态，不是故障。随时 Ctrl-C，下次重跑接着来。
 *
 * 续跑为什么不会画风走样：seed 只由商品 id 决定（见 art-direction.mjs 第 1 条），
 * 所以今天生成的视角 1 和下周生成的视角 2、3 仍然是同一件东西。
 *
 * 用法：
 *   node --import ./scripts/ts-resolve.mjs scripts/gen-images.mjs              # 按优先级一直跑
 *   node --import ./scripts/ts-resolve.mjs scripts/gen-images.mjs --limit 100  # 只跑 100 张
 *   node --import ./scripts/ts-resolve.mjs scripts/gen-images.mjs --tier 1     # 只跑某一档
 *   node --import ./scripts/ts-resolve.mjs scripts/gen-images.mjs --plan       # 只看计划，不联网
 *
 * 产物：public/img/<id>.jpg（视角 1）、<id>-v2.jpg、<id>-v3.jpg
 * 跑完记得： node --import ./scripts/ts-resolve.mjs scripts/build-image-manifest.mjs
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, renameSync, statSync, unlinkSync, writeFileSync, appendFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { promptFor, seedOf, shouldGenerate, VIEWS_PER_PRODUCT } from './art-direction.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const IMG_DIR = join(ROOT, 'public', 'img')
const LOG = join(ROOT, 'scripts', '.gen-images.log')
const AI_RECORD = join(ROOT, 'scripts', 'ai-sourced.json')

const argv = process.argv.slice(2)
const flag = (name, fallback) => {
  const i = argv.indexOf(`--${name}`)
  return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : fallback
}
const has = (name) => argv.includes(`--${name}`)

const MODEL = flag('model', 'flux')
const LIMIT = Number(flag('limit', Infinity))
const ONLY_TIER = flag('tier', null)
const BREADTH = has('breadth')
const PLAN_ONLY = has('plan')

const MIN_BYTES = 25_000
const MAX_ATTEMPTS = 3

const { PRODUCTS, SALON_PRODUCTS } = await import(join(ROOT, 'src/lib/products.ts'))
const { maisonHero, MAISONS } = await import(join(ROOT, 'src/lib/maisons.ts'))

/** `-v2` 而不是 `-2`：商品 id 里已经有 `lx-mini-sub-2` 这种货色，
    用 `-2` 的话它的主图会和 `lx-mini-sub` 的第二视角撞成同一个文件名。 */
const pathFor = (id, view) => join(IMG_DIR, view === 1 ? `${id}.jpg` : `${id}-v${view}.jpg`)
const hasView = (id, view) => existsSync(pathFor(id, view))

/* ------------------------------------------------- 哪些主图动得，哪些动不得

   动不得：真人拍的照片（Unsplash / CC BY / CC BY-SA）。CLAUDE.md 把 Unsplash 排在
   AI 前面，CC BY 还带署名义务——一张好的真实照片胜过三张 AI 视角，这些只保留单视角。
   动得：本流水线自己生成的 AI 图。它们可以按新 seed 重画，好让三个视角是同一件东西。
------------------------------------------------------------------------- */
const aiSourced = new Set(JSON.parse(readFileSync(AI_RECORD, 'utf8')).ids)
const remember = (id) => {
  if (aiSourced.has(id)) return
  aiSourced.add(id)
  writeFileSync(AI_RECORD, `${JSON.stringify({ note: AI_NOTE, ids: [...aiSourced].sort() }, null, 2)}\n`)
}
const AI_NOTE =
  'Product ids whose photography is AI-generated by scripts/gen-images.mjs and may therefore be re-generated. ' +
  'Ids absent from this list have real photography (Unsplash / CC BY / CC BY-SA, see src/lib/credits.ts) and must not be overwritten.'

/* ---------------------------------------------------------------- 优先级

   Tier 1  已有 AI 主图的商品 → 重画三视角（三张同 seed，终于是同一件东西了）
   Tier 2  高可见度但没有图的商品 → 三视角（品牌屋门面 / 沙龙 / 配货款 / 贵价款）
   Tier 3  长尾商品 → 先只补主图（目录页的格子先有照片，比谁都先看得见）
   Tier 4  长尾商品 → 再补第 2、3 视角
------------------------------------------------------------------- */
const heroIds = new Set(MAISONS.map((m) => maisonHero(m.id)?.id).filter(Boolean))
const salonIds = new Set(SALON_PRODUCTS.map((p) => p.id))

function visibility(p) {
  let score = 0
  if (heroIds.has(p.id)) score += 1000
  if (salonIds.has(p.id)) score += 500
  if (p.quota) score += 250
  return score
}
const byVisibility = (a, b) => visibility(b) - visibility(a) || b.price - a.price

/** 有真人照片的：不碰。 */
const isProtected = (p) => hasView(p.id, 1) && !aiSourced.has(p.id)

const queue = []
const push = (tier, p, view, overwrite = false) => {
  if (!overwrite && hasView(p.id, view)) return
  queue.push({ tier, id: p.id, view, overwrite, prompt: promptFor(p, view), seed: seedOf(p.id) })
}

const aiProducts = PRODUCTS.filter((p) => aiSourced.has(p.id) && shouldGenerate(p)).sort(byVisibility)
const openProducts = PRODUCTS.filter((p) => !isProtected(p) && !aiSourced.has(p.id) && shouldGenerate(p)).sort(byVisibility)

// tier 1：主图也重画（overwrite），三张同 seed 才配得上叫「同一件的三个视角」
for (const p of aiProducts) for (let v = 1; v <= VIEWS_PER_PRODUCT; v++) push(1, p, v, v === 1 && !hasView(p.id, 2))
for (const p of openProducts.filter((p) => visibility(p) > 0)) for (let v = 1; v <= VIEWS_PER_PRODUCT; v++) push(2, p, v)
for (const p of openProducts.filter((p) => visibility(p) === 0)) push(3, p, 1)
for (const p of openProducts.filter((p) => visibility(p) === 0)) for (const v of [2, 3]) push(4, p, v)

/**
 * --breadth：先把**每一件**的主图铺满，再回头补第 2、3 视角。
 *
 * 默认顺序是「一件补齐三视角，再下一件」，于是逛目录时会看到一小撮商品有完整画廊、
 * 而几百件还是空展签——「怎么这么多图没有」。广度优先把 view 1 全部提到前面，
 * 每一格先有一张图，画廊留到最后补。免费通道下这是让目录「看起来齐了」最快的排法。
 */
let ordered = ONLY_TIER ? queue.filter((j) => j.tier === Number(ONLY_TIER)) : queue
if (BREADTH) {
  ordered = [...ordered].sort((a, b) => a.view - b.view || a.tier - b.tier)
}
const work = ordered.slice(0, LIMIT)

const onDisk = PRODUCTS.reduce((n, p) => n + [1, 2, 3].filter((v) => hasView(p.id, v)).length, 0)
const tierCount = (t) => queue.filter((j) => j.tier === t).length
console.log(`catalogue       ${PRODUCTS.length} pieces, ${onDisk} view files on disk`)
console.log(`protected       ${PRODUCTS.filter(isProtected).length} pieces have real photography (left alone, single view)`)
console.log(`ai-sourced      ${aiProducts.length} pieces re-generatable`)
console.log(`queue           tier1 ${tierCount(1)} · tier2 ${tierCount(2)} · tier3 ${tierCount(3)} · tier4 ${tierCount(4)} = ${queue.length} images to make`)
console.log(`this run        ${work.length} images, model=${MODEL}, ~${((work.length * 44) / 3600).toFixed(1)}h at the observed rate`)
if (PLAN_ONLY) {
  for (const j of work.slice(0, 6)) console.log(`  [t${j.tier}] ${j.id} v${j.view}${j.overwrite ? ' (redraw)' : ''}\n      ${j.prompt.slice(0, 140)}…`)
  process.exit(0)
}

/* ---------------------------------------------------------------- 抓取 */

let delayMs = 4000
const MIN_DELAY = 3000
const MAX_DELAY = 90_000
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

let made = 0
let failed = 0
const startedAt = Date.now()
let stopping = false
process.on('SIGINT', () => {
  console.log('\n收到中断，跑完这张就停。重跑本脚本会从断点继续（seed 由 id 决定，接得上）。')
  stopping = true
})

const url = (job) =>
  `https://image.pollinations.ai/prompt/${encodeURIComponent(job.prompt)}` +
  `?width=768&height=1024&nologo=true&model=${MODEL}&seed=${job.seed}`

/** 下载 → 验真（真 JPEG 且够大）→ 压到 700px 宽。任一步失败都不留半张图。 */
async function fetchOne(job) {
  const dest = pathFor(job.id, job.view)
  const tmp = `${dest}.part`

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const ctrl = new AbortController()
      const t = setTimeout(() => ctrl.abort(), 120_000)
      const res = await fetch(url(job), { signal: ctrl.signal })
      clearTimeout(t)

      if (res.status === 429) {
        delayMs = Math.min(MAX_DELAY, delayMs * 2)
        await sleep(delayMs)
        continue
      }
      if (!res.ok) throw new Error(`HTTP ${res.status}`)

      const buf = Buffer.from(await res.arrayBuffer())
      if (buf.length < MIN_BYTES) throw new Error(`too small (${buf.length}B)`)
      if (buf[0] !== 0xff || buf[1] !== 0xd8) throw new Error('not a JPEG')

      writeFileSync(tmp, buf)
      execFileSync('sips', ['-Z', '700', tmp], { stdio: 'ignore' })
      if (statSync(tmp).size < MIN_BYTES / 3) throw new Error('degenerate after resize')
      renameSync(tmp, dest)
      remember(job.id)
      return true
    } catch (err) {
      if (existsSync(tmp)) unlinkSync(tmp)
      if (attempt === MAX_ATTEMPTS) {
        appendFileSync(LOG, `FAIL ${job.id} v${job.view} ${err.message}\n`)
        return false
      }
      await sleep(delayMs * attempt)
    }
  }
  return false
}

appendFileSync(LOG, `\nrun ${new Date().toISOString()} model=${MODEL} jobs=${work.length}\n`)

for (const [i, job] of work.entries()) {
  if (stopping) break
  const t0 = Date.now()
  const ok = await fetchOne(job)
  const took = ((Date.now() - t0) / 1000).toFixed(1)

  if (ok) {
    made++
    delayMs = Math.max(MIN_DELAY, delayMs * 0.9) // 顺利就把节流慢慢收回来
  } else {
    failed++
  }

  const done = i + 1
  const rate = (Date.now() - startedAt) / done / 1000
  const eta = (((work.length - done) * rate) / 60).toFixed(0)
  const line = `[${done}/${work.length}] t${job.tier} ${ok ? '✓' : '✗'} ${job.id} v${job.view} ${took}s (avg ${rate.toFixed(1)}s, eta ${eta}m)`
  console.log(line)
  appendFileSync(LOG, `${line}\n`)

  if (!stopping && done < work.length) await sleep(delayMs)
}

console.log(`\ndone: ${made} made, ${failed} failed, ${((Date.now() - startedAt) / 60000).toFixed(1)} min`)
console.log('next: node --import ./scripts/ts-resolve.mjs scripts/build-image-manifest.mjs')
