#!/usr/bin/env node
/**
 * 商品配图流水线（Flux）。两条通道：
 *   - **pollinations**（默认，免费无 key）：匿名档每 IP 只允许 1 并发，越跑越慢（~40s→几分钟/张），
 *     所以严格串行 + 自适应退避。跑不完是常态，随时 Ctrl-C，重跑续上。
 *   - **fal**（付费，快几十倍）：同样是 Flux，可并发；key 从 .env 的 FAL_KEY 读。
 *   - **openai**（付费，质感最好）：gpt-image-2。主图 t2i；**2/3 视角把主图喂回去 img2img**，
 *     同一件东西换角度重拍——跨视角一致性从「同 seed 的表亲」升级为「同一个实物」。
 *     ~$0.06/张（medium 竖幅），跑前会打印预估费用。key 从 .env 的 OPENAI_API_KEY 读。
 *
 * 续跑为什么不会画风走样：seed 只由商品 id 决定（见 art-direction.mjs 第 1 条），
 * 换通道也一样——fal 和 pollinations 同 seed 出的是同一件东西，可以混着补。
 *
 * 用法（都可加 --breadth：先把每件的主图铺满，再回头补 2、3 视角）：
 *   npm run images                    # 免费通道，广度优先
 *   npm run images:fal                # fal 付费通道，6 并发（需 .env 里的 FAL_KEY）
 *   ... --provider fal --concurrency 10   # 调并发
 *   ... --limit 100 / --tier 1 / --plan   # 限量 / 单档 / 只看计划不联网
 *
 * 产物：public/img/<id>.jpg（视角 1）、<id>-v2.jpg、<id>-v3.jpg
 * 跑完记得： npm run images:manifest
 */
import { execFileSync } from 'node:child_process'
import { existsSync, readFileSync, statSync, unlinkSync, writeFileSync, appendFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { promptFor, seedOf, shouldGenerate, VIEWS_PER_PRODUCT } from './art-direction.mjs'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const IMG_DIR = join(ROOT, 'public', 'img')
const LOG = join(ROOT, 'scripts', '.gen-images.log')
const AI_RECORD = join(ROOT, 'scripts', 'ai-sourced.json')

// 从 .env 读 FAL_KEY（node 不会自动加载 .env）；已在环境里的不覆盖
try {
  for (const line of readFileSync(join(ROOT, '.env'), 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$/)
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2].replace(/^["']|["']$/g, '')
  }
} catch {
  /* 没有 .env 也没关系，只有 fal 通道才需要 key */
}

const argv = process.argv.slice(2)
const flag = (name, fallback) => {
  const i = argv.indexOf(`--${name}`)
  return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : fallback
}
const has = (name) => argv.includes(`--${name}`)

const MODEL = flag('model', 'flux')
const LIMIT = Number(flag('limit', Infinity))
const ONLY_TIER = flag('tier', null)
const BREADTH = has('breadth')

/**
 * 图源。pollinations = 免费但每 IP 单并发、越跑越慢；fal = 付费但可并发（快几十倍），
 * 同样是 Flux，出图风格与免费通道一致。key 从 .env 的 FAL_KEY 读。
 */
const PROVIDER = flag('provider', 'pollinations')
/** --only id1,id2：只补这些商品（点名重画用）；配 --redraw 强制重画已存在的 */
const ONLY_IDS = (flag('only', '') || '').split(',').filter(Boolean)
const REDRAW = argv.includes('--redraw')
const CONCURRENCY = PROVIDER === 'fal' ? Math.max(1, Number(flag('concurrency', 6))) : PROVIDER === 'openai' ? Math.max(1, Number(flag('concurrency', 4))) : 1
const PLAN_ONLY = has('plan')

const MIN_BYTES = 25_000
const MAX_ATTEMPTS = 3

const { PRODUCTS, SALON_PRODUCTS } = await import(join(ROOT, 'src/lib/products.ts'))
const { maisonHero, MAISONS } = await import(join(ROOT, 'src/lib/maisons.ts'))

/** `-v2` 而不是 `-2`：商品 id 里已经有 `lx-mini-sub-2` 这种货色，
    用 `-2` 的话它的主图会和 `lx-mini-sub` 的第二视角撞成同一个文件名。 */
const pathFor = (id, view) => join(IMG_DIR, view === 1 ? `${id}.jpg` : `${id}-v${view}.jpg`)
const hasView = (id, view) => existsSync(pathFor(id, view))

/* ------------------------------------------------- 哪些主图动得，哪些动不得

   动不得：真人拍的照片（Unsplash / CC BY / CC BY-SA）。CLAUDE.md 把 Unsplash 排在
   AI 前面，CC BY 还带署名义务——一张好的真实照片胜过三张 AI 视角，这些只保留单视角。
   动得：本流水线自己生成的 AI 图。它们可以按新 seed 重画，好让三个视角是同一件东西。
------------------------------------------------------------------------- */
const aiSourced = new Set(JSON.parse(readFileSync(AI_RECORD, 'utf8')).ids)
const remember = (id) => {
  if (aiSourced.has(id)) return
  aiSourced.add(id)
  writeFileSync(AI_RECORD, `${JSON.stringify({ note: AI_NOTE, ids: [...aiSourced].sort() }, null, 2)}\n`)
}
const AI_NOTE =
  'Product ids whose photography is AI-generated by scripts/gen-images.mjs and may therefore be re-generated. ' +
  'Ids absent from this list have real photography (Unsplash / CC BY / CC BY-SA, see src/lib/credits.ts) and must not be overwritten.'

/* ---------------------------------------------------------------- 优先级

   Tier 1  已有 AI 主图的商品 → 重画三视角（三张同 seed，终于是同一件东西了）
   Tier 2  高可见度但没有图的商品 → 三视角（品牌屋门面 / 沙龙 / 配货款 / 贵价款）
   Tier 3  长尾商品 → 先只补主图（目录页的格子先有照片，比谁都先看得见）
   Tier 4  长尾商品 → 再补第 2、3 视角
------------------------------------------------------------------- */
const heroIds = new Set(MAISONS.map((m) => maisonHero(m.id)?.id).filter(Boolean))
const salonIds = new Set(SALON_PRODUCTS.map((p) => p.id))

function visibility(p) {
  let score = 0
  if (heroIds.has(p.id)) score += 1000
  if (salonIds.has(p.id)) score += 500
  if (p.quota) score += 250
  return score
}
const byVisibility = (a, b) => visibility(b) - visibility(a) || b.price - a.price

/** 有真人照片的：不碰。 */
const isProtected = (p) => hasView(p.id, 1) && !aiSourced.has(p.id)

const queue = []
const push = (tier, p, view, overwrite = false) => {
  if (REDRAW && ONLY_IDS.includes(p.id)) overwrite = true
  if (!overwrite && hasView(p.id, view)) return
  queue.push({ tier, id: p.id, view, overwrite, prompt: promptFor(p, view), seed: seedOf(p.id) })
}

const aiProducts = PRODUCTS.filter((p) => aiSourced.has(p.id) && shouldGenerate(p)).sort(byVisibility)
const openProducts = PRODUCTS.filter((p) => !isProtected(p) && !aiSourced.has(p.id) && shouldGenerate(p)).sort(byVisibility)

// tier 1：seed 通道下主图要陪着重画（三张同 seed 才叫同一件）；
// openai 通道恰恰相反——主图是 2/3 视角的参照物，**绝不能**重画
for (const p of aiProducts) for (let v = 1; v <= VIEWS_PER_PRODUCT; v++) push(1, p, v, PROVIDER !== 'openai' && v === 1 && !hasView(p.id, 2))
for (const p of openProducts.filter((p) => visibility(p) > 0)) for (let v = 1; v <= VIEWS_PER_PRODUCT; v++) push(2, p, v)
for (const p of openProducts.filter((p) => visibility(p) === 0)) push(3, p, 1)
for (const p of openProducts.filter((p) => visibility(p) === 0)) for (const v of [2, 3]) push(4, p, v)

/**
 * --breadth：先把**每一件**的主图铺满，再回头补第 2、3 视角。
 *
 * 默认顺序是「一件补齐三视角，再下一件」，于是逛目录时会看到一小撮商品有完整画廊、
 * 而几百件还是空展签——「怎么这么多图没有」。广度优先把 view 1 全部提到前面，
 * 每一格先有一张图，画廊留到最后补。免费通道下这是让目录「看起来齐了」最快的排法。
 */
let ordered = ONLY_TIER ? queue.filter((j) => j.tier === Number(ONLY_TIER)) : queue
if (ONLY_IDS.length) ordered = ordered.filter((j) => ONLY_IDS.includes(j.id))
if (BREADTH) {
  ordered = [...ordered].sort((a, b) => a.view - b.view || a.tier - b.tier)
}
const work = ordered.slice(0, LIMIT)

const onDisk = PRODUCTS.reduce((n, p) => n + [1, 2, 3].filter((v) => hasView(p.id, v)).length, 0)
const tierCount = (t) => queue.filter((j) => j.tier === t).length
console.log(`catalogue       ${PRODUCTS.length} pieces, ${onDisk} view files on disk`)
console.log(`protected       ${PRODUCTS.filter(isProtected).length} pieces have real photography (left alone, single view)`)
console.log(`ai-sourced      ${aiProducts.length} pieces re-generatable`)
console.log(`queue           tier1 ${tierCount(1)} · tier2 ${tierCount(2)} · tier3 ${tierCount(3)} · tier4 ${tierCount(4)} = ${queue.length} images to make`)
console.log(`this run        ${work.length} images · provider=${PROVIDER}${PROVIDER === 'fal' ? ` · ${CONCURRENCY} concurrent` : ' · serial (免费单并发)'}`)
if (PLAN_ONLY) {
  for (const j of work.slice(0, 6)) console.log(`  [t${j.tier}] ${j.id} v${j.view}${j.overwrite ? ' (redraw)' : ''}\n      ${j.prompt.slice(0, 140)}…`)
  process.exit(0)
}

if (PROVIDER === 'fal' && !process.env.FAL_KEY) {
  console.error('缺 FAL_KEY：把 fal.ai 的 key 写进 .env（FAL_KEY=xxx），或换 --provider pollinations')
  process.exit(1)
}
if (PROVIDER === 'openai') {
  if (!process.env.OPENAI_API_KEY) {
    console.error('缺 OPENAI_API_KEY：把 platform.openai.com 的 key 写进 .env，或换 --provider pollinations')
    process.exit(1)
  }
  console.log(`openai 通道预估费用：${work.length} 张 × ~$0.06 ≈ $${(work.length * 0.06).toFixed(2)}（medium 竖幅；用 --limit 控制批量）`)
}

/* ---------------------------------------------------------------- 抓取 */

let delayMs = 4000
const MIN_DELAY = 3000
const MAX_DELAY = 90_000
const sleep = (ms) => new Promise((r) => setTimeout(r, ms))

let made = 0
let failed = 0
let done = 0
const startedAt = Date.now()
let stopping = false
process.on('SIGINT', () => {
  console.log('\n收到中断，跑完手上这些就停。重跑本脚本会从断点继续（seed 由 id 决定，接得上）。')
  stopping = true
})

const pollUrl = (job) =>
  `https://image.pollinations.ai/prompt/${encodeURIComponent(job.prompt)}` +
  `?width=768&height=1024&nologo=true&model=${MODEL}&seed=${job.seed}`

/**
 * 取原始图字节。
 * pollinations：GET，响应体本身就是图；429 抛出带标记，交给退避。
 * fal：POST 提示词拿到 json 里的图 url，再下一次；付费、可并发、同样 Flux。
 */
async function rawImage(job, signal) {
  if (PROVIDER === 'openai') {
    const mainPath = pathFor(job.id, 1)
    // 2/3 视角且主图在手：把主图喂回去，同一件实物换角度重拍（一致性的正解）
    if (job.view > 1 && existsSync(mainPath)) {
      const form = new FormData()
      form.append('model', 'gpt-image-2')
      form.append('image[]', new Blob([readFileSync(mainPath)], { type: 'image/jpeg' }), 'ref.jpg')
      form.append('prompt', `Photograph the SAME object shown in the reference image, unchanged in shape, material and colour, from a new angle: ${job.prompt}`)
      form.append('n', '1')
      form.append('size', '1024x1536')
      form.append('quality', 'medium')
      const res = await fetch('https://api.openai.com/v1/images/edits', {
        method: 'POST',
        headers: { authorization: `Bearer ${process.env.OPENAI_API_KEY}` },
        body: form,
        signal,
      })
      if (!res.ok) throw new Error(`openai edits HTTP ${res.status}`)
      const data = await res.json()
      const b64 = data?.data?.[0]?.b64_json
      if (!b64) throw new Error('openai edits: no image')
      return Buffer.from(b64, 'base64')
    }
    const res = await fetch('https://api.openai.com/v1/images/generations', {
      method: 'POST',
      headers: { authorization: `Bearer ${process.env.OPENAI_API_KEY}`, 'content-type': 'application/json' },
      body: JSON.stringify({ model: 'gpt-image-2', prompt: job.prompt, n: 1, size: '1024x1536', quality: 'medium' }),
      signal,
    })
    if (!res.ok) throw new Error(`openai HTTP ${res.status}`)
    const data = await res.json()
    const b64 = data?.data?.[0]?.b64_json
    if (!b64) throw new Error('openai: no image')
    return Buffer.from(b64, 'base64')
  }
  if (PROVIDER === 'fal') {
    const res = await fetch('https://fal.run/fal-ai/flux/schnell', {
      method: 'POST',
      headers: { Authorization: `Key ${process.env.FAL_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({
        prompt: job.prompt,
        image_size: { width: 768, height: 1024 },
        num_inference_steps: 4,
        seed: job.seed,
        num_images: 1,
        output_format: 'jpeg',
        enable_safety_checker: true,
      }),
      signal,
    })
    if (!res.ok) throw new Error(`fal HTTP ${res.status}`)
    const data = await res.json()
    const u = data?.images?.[0]?.url
    if (!u) throw new Error('fal: no image url in response')
    const img = await fetch(u, { signal })
    if (!img.ok) throw new Error(`fal image HTTP ${img.status}`)
    return Buffer.from(await img.arrayBuffer())
  }
  const res = await fetch(pollUrl(job), { signal })
  if (res.status === 429) {
    const e = new Error('429')
    e.rateLimited = true
    throw e
  }
  if (!res.ok) throw new Error(`HTTP ${res.status}`)
  return Buffer.from(await res.arrayBuffer())
}

/** 下载 → 验真（是图且够大）→ 转 jpeg 压到 700px 宽。任一步失败都不留半张图。 */
async function fetchOne(job) {
  const dest = pathFor(job.id, job.view)
  const tmp = `${dest}.part`

  for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
    try {
      const ctrl = new AbortController()
      const t = setTimeout(() => ctrl.abort(), 120_000)
      let buf
      try {
        buf = await rawImage(job, ctrl.signal)
      } finally {
        clearTimeout(t)
      }
      if (buf.length < MIN_BYTES) throw new Error(`too small (${buf.length}B)`)
      const jpg = buf[0] === 0xff && buf[1] === 0xd8
      const png = buf[0] === 0x89 && buf[1] === 0x50
      if (!jpg && !png) throw new Error('not an image')

      writeFileSync(tmp, buf)
      if (PROVIDER === 'openai') {
        // 2:3 → 居中裁 3:4（sips -c 恰好是中心裁切；见 normalise-aspect 的教训——这里要的就是中心）
        execFileSync('sips', ['-c', '1365', '1024', tmp], { stdio: 'ignore' })
      }
      execFileSync('sips', ['-Z', '700', '-s', 'format', 'jpeg', tmp, '--out', dest], { stdio: 'ignore' })
      if (existsSync(tmp)) unlinkSync(tmp)
      if (statSync(dest).size < MIN_BYTES / 3) throw new Error('degenerate after resize')
      remember(job.id)
      return true
    } catch (err) {
      if (existsSync(tmp)) unlinkSync(tmp)
      if (err.rateLimited) {
        // 429 只发生在免费通道；翻倍退避后重试，不消耗尝试次数
        delayMs = Math.min(MAX_DELAY, delayMs * 2)
        await sleep(delayMs)
        attempt--
        continue
      }
      if (attempt === MAX_ATTEMPTS) {
        appendFileSync(LOG, `FAIL ${job.id} v${job.view} ${err.message}\n`)
        return false
      }
      await sleep((PROVIDER === 'fal' ? 1500 : delayMs) * attempt)
    }
  }
  return false
}

function report(job, ok, took) {
  done++
  if (ok) made++
  else failed++
  const rate = (Date.now() - startedAt) / done / 1000
  const eta = (((work.length - done) * rate) / 60).toFixed(0)
  const line = `[${done}/${work.length}] t${job.tier} ${ok ? '✓' : '✗'} ${job.id} v${job.view} ${took}s (avg ${rate.toFixed(1)}s, eta ${eta}m)`
  console.log(line)
  appendFileSync(LOG, `${line}\n`)
}

/** 一个 worker 从共享迭代器里不停取活。CONCURRENCY 个并跑（免费通道恒为 1）。 */
async function worker(iter) {
  for (const job of iter) {
    if (stopping) return
    const t0 = Date.now()
    const ok = await fetchOne(job)
    report(job, ok, ((Date.now() - t0) / 1000).toFixed(1))
    if (PROVIDER === 'pollinations') {
      if (ok) delayMs = Math.max(MIN_DELAY, delayMs * 0.9) // 顺利就把节流慢慢收回来
      if (!stopping) await sleep(delayMs)
    }
  }
}

appendFileSync(LOG, `\nrun ${new Date().toISOString()} provider=${PROVIDER} conc=${CONCURRENCY} jobs=${work.length}\n`)

// 多个 worker 共享同一个数组迭代器；JS 单线程，.next() 原子，不会取到重复
const shared = work[Symbol.iterator]()
await Promise.all(Array.from({ length: CONCURRENCY }, () => worker(shared)))

console.log(`\ndone: ${made} made, ${failed} failed, ${((Date.now() - startedAt) / 60000).toFixed(1)} min`)
console.log('next: node --import ./scripts/ts-resolve.mjs scripts/build-image-manifest.mjs')
